version: "3.7"
services:
  nats:
    container_name: nats-standalone
    image: nats:alpine
    restart: always
    ports: 
      - 4222:4222
      - 8222:8222
    networks:
      - sx-net
networks:
  sx-net:
    external: true # 使用自定义创建好的网络，我创建的网络名加sx-net，方便与其他服务通信
