version: "3.7"
services:
  nats-0:
    container_name: nats-0
    image: nats:alpine
    restart: always
    ports:
      - 4222:4222
      - 8222:8222
    networks:
      - sx-net
  nats-1:
    container_name: nats-1
    image: nats:alpine
    restart: always
    command: "--cluster nats-0://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats-0:6222"
    depends_on:
      - nats-0
    networks:
      - sx-net
  nats-2:
    container_name: nats-2
    image: nats:alpine
    restart: always
    command: "--cluster nats-0://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats-0:6222"
    depends_on:
      - nats-0
    networks:
      - sx-net
networks:
  sx-net:
    external: true # 使用自定义创建好的网络，我创建的网络名加sx-net，方便与其他服务通信
