version: "3.8"
services:
  nginx:
    container_name: sx-nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d # 可以在这个目录下指定nginx的配置文件
      - ./nginx/logs:/var/logs
    networks:
      - sx-net
  emi-note:
    container_name: emi-note
    image: emi-note:0.0.1
    restart: always
    ports:
      - "3000:3000"
    networks:
      - sx-net
networks:
  sx-net:
    external: true # 使用自定义创建好的网络，我创建的网络名加sx-net，方便与其他服务通信
