version: "3.8"

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: minioadmin
    MINIO_SERVER_URL: "http://minio.poine.com"
    MINIO_BROWSER_REDIRECT_URL: "http://minio.poine.com/minio/ui"
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  nginx:
    container_name: sx-nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d # 可以在这个目录下指定nginx的配置文件
      - ./nginx/logs:/var/logs
    networks:
      - sx-net
  emi-note:
    container_name: emi-note
    image: emi-note:0.0.1
    restart: always
    ports:
      - 3000
    networks:
      - sx-net
  minderly-dashboard:
    container_name: minderly-dashboard
    image: minderly-dashboard:0.0.1
    restart: always
    ports:
      - 3000
    networks:
      - sx-net
  minio1:
    <<: *minio-common
    hostname: minio1
    container_name: minio1
    volumes:
      - ./minio/data1-1:/data1
      - ./minio/data1-2:/data2
    extra_hosts:
      - "minio.poine.com:sx-nginx"
    networks:
      - sx-net
  minio2:
    <<: *minio-common
    hostname: minio2
    container_name: minio2
    volumes:
      - ./minio/data2-1:/data1
      - ./minio/data2-2:/data2
    extra_hosts:
      - "minio.poine.com:sx-nginx"
    networks:
      - sx-net
  minio3:
    <<: *minio-common
    hostname: minio3
    container_name: minio3
    volumes:
      - ./minio/data3-1:/data1
      - ./minio/data3-2:/data2
    extra_hosts:
      - "minio.poine.com:sx-nginx"
    networks:
      - sx-net
  minio4:
    <<: *minio-common
    hostname: minio4
    container_name: minio4
    volumes:
      - ./minio/data4-1:/data1
      - ./minio/data4-2:/data2
    extra_hosts:
      - "minio.poine.com:sx-nginx"
    networks:
      - sx-net
networks:
  sx-net:
    external: true # 使用自定义创建好的网络，我创建的网络名加sx-net，方便与其他服务通信
