version: '3.8'

services:
  master:
    image: chrislusf/seaweedfs # use a remote image
    container_name: sx-weed-master-dev
    ports:
      - 9333:9333
      - 19333:19333
    command: "master -ip=sx-weed-master-dev"
    networks:
      - sx-net
  volume1:
    image: chrislusf/seaweedfs # use a remote image
    container_name: sx-weed-volume-dev1
    ports:
      - 8080:8080
    command: 'volume -mserver="sx-weed-master-dev:9333" -port=8080 -ip=sx-weed-volume-dev1 -publicUrl=cdn.dmtech.com'
    depends_on:
      - master
    networks:
      - sx-net
  volume2:
    image: chrislusf/seaweedfs # use a remote image
    container_name: sx-weed-volume-dev2
    ports:
      - 8081:8081
    command: 'volume -mserver="sx-weed-master-dev:9333" -port=8081 -ip=sx-weed-volume-dev2 -publicUrl=cdn.dmtech.com'
    depends_on:
      - master
    networks:
      - sx-net
  filer:
    image: chrislusf/seaweedfs # use a remote image
    container_name: sx-weed-filer-dev
    ports:
      - 8888:8888
    command: 'filer -master="sx-weed-master-dev:9333"'
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume1
      - volume2
    networks:
      - sx-net
  nginx:
    container_name: sx-weed-nginx-dev
    image: nginx:latest
    restart: always
    user: root
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d # 可以在这个目录下指定nginx的配置文件
    networks:
      - sx-net
networks:
  sx-net:
    external: true